version: '3.3'
services:
  mysql:
     image: ubuntu/mysql:latest
     restart: always
     environment:
       MYSQL_DATABASE: 'aslam_db'
       # So you don't have to use root, but you can if you like
       MYSQL_USER: 'aslam'
       # You can use whatever password you like
       MYSQL_PASSWORD: 'aslam_pass'
       # Password for root access
       MYSQL_ROOT_PASSWORD: 'aslam_root_password'
     networks:
       images_net:
         ipv4_address: 10.2.0.3

     expose:
       # Opens port 3306 on the container
       - '3306'
       # Where our data will be persisted

networks:
  images_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
          gateway: 10.2.0.1