spring:
  datasource:
    password: ${mysql_password}
    url: jdbc:mysql://${mysql_ip}:3306/${mysql_db}
    username: ${mysql_user}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



