version: '3.3'
services:
  mysql:
    image: ubuntu/mysql:latest
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: ${db_name}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${db_user}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${db_password}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${db_root_password}
      #mount dirctory mysql conf to access any ip from other container
    volumes:
      - './mysql_conf:/etc/mysql/conf.d'

    networks:
      images_net:
        ipv4_address: 10.2.0.3

    expose:
      - '3306'

  productImagesApi:
    image: aslamimages/product_images:latest
    restart: always
    depends_on:
      - mysql
    environment:
      mysql_user: ${db_user}
      mysql_password: ${db_password}
      mysql_db: ${db_name}
      mysql_ip: 10.2.0.3
    expose:
      - '3306'
    ports:
      - "8089:8080"
    networks:
      images_net:
        ipv4_address: 10.2.0.4

networks:
  images_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
          gateway: 10.2.0.1
